unit UNBCSTP;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  quickrpt, ExtCtrls, Qrctrls;

type
  TFMBCSTP = class(TForm)
    QuickRep: TQuickRep;
    QRBand4: TQRBand;
    QRShape5: TQRShape;
    QRShape8: TQRShape;
    LBBSENO: TQRLabel;
    LBBSNAM: TQRLabel;
    LBBSMN1: TQRLabel;
    LBBSCNA: TQRLabel;
    LBBSMN3: TQRLabel;
    LBBSMN2: TQRLabel;
    LBBSTL1: TQRLabel;
    LBBSFX1: TQRLabel;
    QRShape9: TQRShape;
    QRShape15: TQRShape;
    LBBSAD1: TQRLabel;
    QRShape20: TQRShape;
    LBBSMRK: TQRLabel;
    LBBSID1: TQRLabel;
    QRShape22: TQRShape;
    QRBand5: TQRBand;
    QRLabel7: TQRLabel;
    QRBand6: TQRBand;
    QRDBText1: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText11: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText14: TQRDBText;
    QRDBText15: TQRDBText;
    QRLabel11: TQRDBText;
    QRLabel12: TQRDBText;
    QRLabel13: TQRDBText;
    QRLabel14: TQRDBText;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape4: TQRShape;
    QRShape6: TQRShape;
    QRShape3: TQRShape;
    QRShape7: TQRShape;
    QRShape10: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape21: TQRShape;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  FMBCSTP: TFMBCSTP;

implementation

USES UNBCSTD;

{$R *.DFM}












































end.
